import random

# number is randomly generated by 'random module' in the range of 1 to 100
number = random.randint(1, 100)

# guess is defined by player, and it's set to get number by 'int' for 'input'
guess = int(input("Write number to guess: "))

while number != guess:
    if guess > number:
        print("Number is lower!")
        guess = int(input("Write number to guess: "))

    elif guess < number:
        print("Number is higher!")
        guess = int(input("Write number to guess: "))

    else:
        break
print("Congrats! You guessed a number!")
